// <auto-generated />
using System;
using AbpAspNetCoreDemo.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AbpAspNetCoreDemo.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20190726061557_Initial_Migration")]
    partial class Initial_Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview7.19362.6");

            modelBuilder.Entity("AbpAspNetCoreDemo.Core.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<long?>("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<float?>("Price");

                    b.HasKey("Id");

                    b.ToTable("AppProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationTime = new DateTime(2019, 7, 26, 9, 15, 57, 82, DateTimeKind.Local).AddTicks(4827),
                            IsDeleted = false,
                            Name = "Test product",
                            Price = 100f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
